name: Docker
on:
  push:
    branches:
      - docker-humble
  pull_request:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/moon
  REGISTRY_IMAGE_HUMBLE: ghcr.io/${{ github.repository_owner }}/moon:humble
  RAW_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  build:
    name: Build and push docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Pull humble image for caching
        run: |
          docker pull ${{ env.REGISTRY_IMAGE_HUMBLE }}
        continue-on-error: true
      - name: Build Docker image
        run: docker build -f .docker/Dockerfile -t ${{ env.REGISTRY_IMAGE_HUMBLE }} .
      - name: Push to gh registry with sha and humble tag (only from the humble branch)
        if: github.ref == 'refs/heads/docker-humble'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker tag ${{ env.REGISTRY_IMAGE_HUMBLE }} ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}
          
          docker push ${{ env.REGISTRY_IMAGE_HUMBLE }}
          echo "TAG_NAME=humble" >> $GITHUB_ENV
